name: Master pull-request merge reaction
on:
  pull_request:
    types: [closed]
    branches:
    - 'master'
env:
  ci_bot_username: ObyBotCI
  ci_bot_email: 104651589+ObyBotCI@users.noreply.github.com
  
jobs:
  tag_master_and_sync_dev:
    name: Tag master merge commit, FF back to dev
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    outputs:
      version_tag: ${{ steps.tag_master.outputs.new_tag }}
    steps:
    - name: Checkout OBCMake Master
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup git user for bot
      run: |
        git config --global user.name "${{ env.ci_bot_username }}"
        git config --global user.email "${{ env.ci_bot_email }}"
    - name: Tag master with new version tag
      id: tag_master
      env:
        match_start: set\(OB_CMAKE_BASE_VERSION
        match_end: \)
      run: |
        $project_lists = Get-Content -Raw CMakeLists.txt
        if(!($project_lists -match '(?<=${{ env.match_start }})(.*)(?=${{ env.match_end }})')){
          throw "Could not get base version!"
        }
        $new_tag = "v$($Matches[1].Trim())"
        echo "new_tag=$new_tag" >> $Env:GITHUB_OUTPUT
        git tag -a $new_tag -m "Release $new_tag"
        git push --tags
    - name: Move 'latest' tag
      run: |
        echo "Checking for 'latest' tag..."
        if(git tag -l latest){
          echo "Removing previous 'latest' tag..."
          git tag -d latest # Delete tag locally
          git push origin :refs/tags/latest # Delete tag remotely
        }
        else{
          echo "No tag to remove."
        }
        git tag -a latest -m "Latest Release"
        git push origin latest
    - name: Fast-forward merge master into to dev
      if: always()
      run: |
        git checkout dev
        git merge master --ff-only
        git push