name: Master pull-request merge reaction
on:
  pull_request:
    types: [closed]
    branches:
    - 'master'
    
jobs:
  tag_master_and_sync_dev:
    name: Tag master merge commit, FF back to dev
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    steps:
    - name: Get project version
      id: get-proj-ver
      uses: oblivioncth/actions/cmake/get-project-version@dev
    - name: Set Git user to ObyBotCI
      uses: oblivioncth/actions/git/set-git-user-to-oby-bot@dev
    - name: Checkout Project
      id: proj-checkout
      uses: oblivioncth/actions/git/smart-checkout@dev
    - name: Tag master with new version tag
      uses: oblivioncth/actions/git/tag@dev
      with:
        tag: 'v${{ steps.get-proj-ver.outputs.version }}'
        message: 'Release v${{ steps.get-proj-ver.outputs.version }}'
    - name: Move 'latest' tag
      uses: oblivioncth/actions/git/move-latest-tag@dev
    - name: Fast-forward merge master into to dev
      if: always()
      uses: oblivioncth/actions/git/merge-branches@dev
      with:
        source_branch: master
        target_branch: dev
        ff: only