name: Master pull-request merge reaction
on:
  pull_request:
    types: [closed]
    branches:
    - 'master'
    
jobs:
  tag_master_and_sync_dev:
    name: Tag master merge commit, FF back to dev
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    outputs:
      version_tag: ${{ steps.tag_master.outputs.new_tag }}
    steps:
    - name: Get project version
      id: get-proj-ver
      uses: oblivioncth/actions/cmake/get-project-version@dev
    - name: Set Git user to ObyBotCI
      uses: oblivioncth/actions/git/set-git-user-to-oby-bot@dev
    - name: Checkout Project
      id: proj-checkout
      uses: oblivioncth/actions/git/smart-checkout@dev
    - name: Tag master with new version tag
      id: tag_master
      working-directory: ${{ steps.proj-checkout.outputs.path }}
      env:
        new_version: ${{ steps.get-proj-ver.outputs.version }}
      run: |
        $new_tag = "v${Env:new_version}"
        echo "new_tag=$new_tag" >> $Env:GITHUB_OUTPUT
        git tag -a $new_tag -m "Release $new_tag"
        git push --tags
    - name: Move 'latest' tag
      working-directory: ${{ steps.proj-checkout.outputs.path }}
      run: |
        echo "Checking for 'latest' tag..."
        if(git tag -l latest){
          echo "Removing previous 'latest' tag..."
          git tag -d latest # Delete tag locally
          git push origin :refs/tags/latest # Delete tag remotely
        }
        else{
          echo "No tag to remove."
        }
        git tag -a latest -m "Latest Release"
        git push origin latest
    - name: Fast-forward merge master into to dev
      if: always()
      working-directory: ${{ steps.proj-checkout.outputs.path }}
      run: |
        git checkout dev
        git merge master --ff-only
        git push